// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Photos.Web;

#nullable disable

namespace Photos.Web.Migrations
{
    [DbContext(typeof(PhotoContext))]
    [Migration("20221022220802_InitialSchema")]
    partial class InitialSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("Photos.Shared.AccessCode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Deactivated")
                        .HasColumnType("TEXT");

                    b.Property<long>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("AccessCodes");
                });

            modelBuilder.Entity("Photos.Shared.AccessRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AcceptedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeniedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("DesiredSeason")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AccessRequests");
                });

            modelBuilder.Entity("Photos.Shared.Authorization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("SeasonId");

                    b.ToTable("Authorizations");
                });

            modelBuilder.Entity("Photos.Shared.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Photos.Shared.Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Photos.Shared.Organization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryColor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("Photos.Shared.Person", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("Photos.Shared.Photo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Taken")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("Photos.Shared.PrintRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClosedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RequestedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("PrintRequests");
                });

            modelBuilder.Entity("Photos.Shared.PrintRequestPhoto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("PhotoId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PrintRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PhotoId");

                    b.HasIndex("PrintRequestId");

                    b.ToTable("PrintRequestPhotos");
                });

            modelBuilder.Entity("Photos.Shared.Season", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("EndsOn")
                        .HasColumnType("TEXT");

                    b.Property<long?>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("Photos.Shared.SingleUseLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IssuedOn")
                        .HasColumnType("TEXT");

                    b.Property<long>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UsedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("SeasonId");

                    b.ToTable("SingleUseLinks");
                });

            modelBuilder.Entity("Photos.Shared.Team", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<long?>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Photos.Shared.AccessCode", b =>
                {
                    b.HasOne("Photos.Shared.Season", "Season")
                        .WithMany("AccessCodes")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Photos.Shared.Authorization", b =>
                {
                    b.HasOne("Photos.Shared.Person", "Person")
                        .WithMany("Authorizations")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Photos.Shared.Season", "Season")
                        .WithMany("Authorizations")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Photos.Shared.Event", b =>
                {
                    b.HasOne("Photos.Shared.Season", null)
                        .WithMany("Events")
                        .HasForeignKey("SeasonId");
                });

            modelBuilder.Entity("Photos.Shared.Organization", b =>
                {
                    b.HasOne("Photos.Shared.Category", null)
                        .WithMany("Organizations")
                        .HasForeignKey("CategoryId");
                });

            modelBuilder.Entity("Photos.Shared.Photo", b =>
                {
                    b.HasOne("Photos.Shared.Event", null)
                        .WithMany("Photos")
                        .HasForeignKey("EventId");
                });

            modelBuilder.Entity("Photos.Shared.PrintRequest", b =>
                {
                    b.HasOne("Photos.Shared.Person", "Person")
                        .WithMany("PrintRequests")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Photos.Shared.PrintRequestPhoto", b =>
                {
                    b.HasOne("Photos.Shared.Photo", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Photos.Shared.PrintRequest", "PrintRequest")
                        .WithMany("Photos")
                        .HasForeignKey("PrintRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");

                    b.Navigation("PrintRequest");
                });

            modelBuilder.Entity("Photos.Shared.Season", b =>
                {
                    b.HasOne("Photos.Shared.Team", null)
                        .WithMany("Seasons")
                        .HasForeignKey("TeamId");
                });

            modelBuilder.Entity("Photos.Shared.SingleUseLink", b =>
                {
                    b.HasOne("Photos.Shared.Person", "Person")
                        .WithMany("SingleUseLinks")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Photos.Shared.Season", "Season")
                        .WithMany("SingleUseLinks")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Photos.Shared.Team", b =>
                {
                    b.HasOne("Photos.Shared.Organization", null)
                        .WithMany("Teams")
                        .HasForeignKey("OrganizationId");
                });

            modelBuilder.Entity("Photos.Shared.Category", b =>
                {
                    b.Navigation("Organizations");
                });

            modelBuilder.Entity("Photos.Shared.Event", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("Photos.Shared.Organization", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Photos.Shared.Person", b =>
                {
                    b.Navigation("Authorizations");

                    b.Navigation("PrintRequests");

                    b.Navigation("SingleUseLinks");
                });

            modelBuilder.Entity("Photos.Shared.PrintRequest", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("Photos.Shared.Season", b =>
                {
                    b.Navigation("AccessCodes");

                    b.Navigation("Authorizations");

                    b.Navigation("Events");

                    b.Navigation("SingleUseLinks");
                });

            modelBuilder.Entity("Photos.Shared.Team", b =>
                {
                    b.Navigation("Seasons");
                });
#pragma warning restore 612, 618
        }
    }
}
